### ISSUE TITLE
Can't download one pdf file.

### ISSUE THREAD

**Issue by solo-code** [Nixonite/open-source-machine-learning-degree#3]
I am in China. The file of Computer Vision: Algorithms and Applications by Richard Szeliski can not be downloaded. Can you send me one copy or upload to a cloud disk?

**Comment by sjqtentacles** [comment]
I'm trying not to host copyrighted material directly on this repository. I just checked the link, and it works for me. Did you try using Tor?

**Comment by solo-code** [comment]
Ok ,Thanks.
