### ISSUE TITLE
Please adjust the link to my Linear Algebra

### ISSUE THREAD

**Issue by jimhefferon** [Nixonite/open-source-machine-learning-degree#4]
I appreciate your work on open materials.   Please adjust the link to my Linear Algebra book.  It currently points to the .pdf but a person who clicks on it would not know that the home page contains a solutions manual with worked solutions to all exercises, slides for lectures, a lab manual for use with *Sage*, and other ancillary materials that self-learners find especially useful.

The best link is http://joshua.smcvt.edu/linearalgebra .

Thank you, Jim

**Comment by sjqtentacles** [comment]
fixed, thanks for the input, didn't even realize I had issues in my repo until now (several months later)
